<?php

namespace Pionia\Performance;

/**
 * Generates storage/bootstrap/preload.php with opcache_compile_file() calls.
 */
final class PreloadGenerator
{
    public function __construct(
        private readonly string $appRoot,
    ) {
    }

    /**
     * @param list<string>|null $scanRoots When set, skips manifest resolution (framework release).
     * @return array{path: string, files: int}
     */
    public function generate(?string $outputPath = null, ?array $scanRoots = null): array
    {
        if ($scanRoots !== null) {
            $excludeFragments = PreloadManifest::defaultExcludeFragments();
        } else {
            $settings = PreloadManifest::fromSettings($this->appRoot);
            $scanRoots = PreloadManifest::resolveScanRoots($this->appRoot, $settings);
            $excludeFragments = PreloadManifest::resolveExcludeFragments($settings);
        }

        $files = $this->collectFiles($scanRoots, $excludeFragments);
        $target = $outputPath ?? $this->defaultOutputPath();

        $directory = dirname($target);
        if (!is_dir($directory)) {
            mkdir($directory, 0775, true);
        }

        $contents = $this->render($files);
        file_put_contents($target, $contents);

        return [
            'path' => $target,
            'files' => count($files),
        ];
    }

    public function defaultOutputPath(): string
    {
        return $this->appRoot . DIRECTORY_SEPARATOR . 'storage' . DIRECTORY_SEPARATOR . 'bootstrap' . DIRECTORY_SEPARATOR . 'preload.php';
    }

    /**
     * @param list<string> $scanRoots
     * @param list<string> $excludeFragments
     *
     * @return list<string>
     */
    private function collectFiles(array $scanRoots, array $excludeFragments): array
    {
        $files = [];

        foreach ($scanRoots as $root) {
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($root, \FilesystemIterator::SKIP_DOTS),
            );

            foreach ($iterator as $file) {
                if (!$file instanceof \SplFileInfo || !$file->isFile()) {
                    continue;
                }

                if (strtolower($file->getExtension()) !== 'php') {
                    continue;
                }

                $path = $file->getPathname();
                if ($this->isExcluded($path, $excludeFragments)) {
                    continue;
                }

                $files[] = $path;
            }
        }

        sort($files);

        return array_values(array_unique($files));
    }

    /**
     * @param list<string> $excludeFragments
     */
    private function isExcluded(string $path, array $excludeFragments): bool
    {
        $normalized = str_replace('\\', '/', $path);

        foreach ($excludeFragments as $fragment) {
            if (str_contains($normalized, str_replace('\\', '/', $fragment))) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param list<string> $files
     */
    private function render(array $files): string
    {
        $lines = [
            '<?php',
            '',
            '/**',
            ' * OPcache preload script — generated by `php pionia optimize`.',
            ' * Loaded via bootstrap/preload.php (php.ini opcache.preload).',
            ' */',
            '',
            'if (!function_exists(\'opcache_compile_file\')) {',
            '    return;',
            '}',
            '',
        ];

        foreach ($files as $file) {
            $escaped = addslashes($file);
            $lines[] = "opcache_compile_file('{$escaped}');";
        }

        $lines[] = '';

        return implode(PHP_EOL, $lines);
    }
}
