<?php

namespace Pionia\Documentation;

use Pionia\Documentation\Contracts\ActionDoc;
use Pionia\Documentation\Contracts\MoonlightApiCatalog;
use Pionia\Documentation\Contracts\ServiceDoc;

class MarkdownExporter
{
    public function export(MoonlightApiCatalog $catalog): string
    {
        $lines = [
            '# ' . $catalog->title . ' — API Reference',
            '',
            '> Generated by `pionia api:docs`. Interactive docs: `/docs` (debug) or `index.html` after `api:docs --ui`.',
            '',
            'All actions use **Moonlight dispatch** — send JSON to a versioned base path:',
            '',
            '```json',
            '{ "service": "<alias>", "action": "<action>", "...params" }',
            '```',
            '',
            '**Response envelope:** `returnCode`, `returnMessage`, `returnData`, `extraData`.',
            '',
        ];

        foreach ($catalog->versions as $version => $services) {
            $base = rtrim(apiVersionPath($version), '/');
            $lines[] = '---';
            $lines[] = '';
            $lines[] = '## API `' . $version . '`';
            $lines[] = '';
            $lines[] = '| | |';
            $lines[] = '|---|---|';
            $lines[] = '| Base URL | `' . $base . '` |';
            $lines[] = '| Method | `POST` (primary), `GET` `/' . $version . '/{service}/{action}/` |';
            $lines[] = '| Health | `GET ' . apiPingPath($version) . '` |';
            $lines[] = '';
            $lines[] = '### Table of contents';
            $lines[] = '';

            ksort($services);

            foreach ($services as $service) {
                $lines[] = '- [' . $service->alias . '](#' . $service->alias . ')';
            }

            $lines[] = '';

            foreach ($services as $service) {
                $lines = array_merge($lines, $this->serviceSection($service, $base));
            }
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * @return list<string>
     */
    private function serviceSection(ServiceDoc $service, string $base): array
    {
        $lines = [
            '---',
            '',
            '## ' . $service->alias,
            '',
        ];

        if ($service->summary) {
            $lines[] = $service->summary;
            $lines[] = '';
        }

        $lines[] = '| | |';
        $lines[] = '|---|---|';
        $lines[] = '| PHP class | `' . $service->className . '` |';
        if ($service->table) {
            $lines[] = '| Table | `' . $service->table . '` |';
        }
        if ($service->auth) {
            $lines[] = '| Default auth | `' . $service->auth . '` |';
        }
        $lines[] = '';

        foreach ($service->actions as $action) {
            $lines = array_merge($lines, $this->operationSection($service, $action, $base));
        }

        return $lines;
    }

    /**
     * @return list<string>
     */
    private function operationSection(ServiceDoc $service, ActionDoc $action, string $base): array
    {
        $summary = $action->summary ?? 'Invoke `' . $action->name . '` on `' . $service->alias . '`.';
        $auth = $action->auth ?? 'none';

        $lines = [
            '### `' . $action->name . '`',
            '',
            $summary,
            '',
            '#### Request',
            '',
            '| | |',
            '|---|---|',
            '| **POST** | `' . $base . '` |',
            '| `service` | `' . $service->alias . '` |',
            '| `action` | `' . $action->name . '` |',
            '| Auth | `' . $auth . '` |',
        ];

        if ($action->permissions !== []) {
            $lines[] = '| Permissions | `' . implode('`, `', $action->permissions) . '` |';
        }

        $lines[] = '';

        if ($action->params !== []) {
            $lines[] = '**Body parameters**';
            $lines[] = '';
            $lines[] = '| Field | Type | Description |';
            $lines[] = '|-------|------|-------------|';
            foreach ($action->params as $name => $meta) {
                $lines[] = sprintf(
                    '| `%s` | %s | %s |',
                    $name,
                    $meta['type'] ?? 'string',
                    $meta['description'] ?? '',
                );
            }
            $lines[] = '';
        }

        $example = $action->example ?? json_encode([
            'service' => $service->alias,
            'action' => $action->name,
        ], JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);

        $lines[] = '**Example**';
        $lines[] = '';
        $lines[] = '```http';
        $lines[] = 'POST ' . $base . ' HTTP/1.1';
        $lines[] = 'Content-Type: application/json';
        $lines[] = '';
        $lines[] = $example;
        $lines[] = '```';
        $lines[] = '';
        $lines[] = '#### Response';
        $lines[] = '';

        if ($action->returnShape) {
            $lines[] = '**`returnData`:** ' . $action->returnShape;
            $lines[] = '';
        }

        $lines[] = '```json';
        $lines[] = json_encode([
            'returnCode' => 0,
            'returnMessage' => 'Success',
            'returnData' => (object) [],
            'extraData' => null,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
        $lines[] = '```';
        $lines[] = '';

        return $lines;
    }
}
